using SmartDoc.Domain.Enums;

namespace SmartDoc.Domain.Entities;

public class Message
{
    public Guid Id { get; private set; }
    public Guid ConversationId { get; private set; }
    public MessageRole Role { get; private set; }

    /// <summary>
    /// For Role == Assistant, this is the full formatted answer including the "Sources:"
    /// list (see ADR 0014 — citations are built deterministically on the .NET side, not
    /// generated by the LLM, then appended here before persisting).
    /// </summary>
    public string Content { get; private set; } = null!;

    public DateTimeOffset CreatedAt { get; private set; }

    // EF Core
    private Message()
    {
    }

    public Message(Guid id, Guid conversationId, MessageRole role, string content, DateTimeOffset createdAt)
    {
        if (id == Guid.Empty)
        {
            throw new ArgumentException("Id cannot be empty.", nameof(id));
        }

        if (conversationId == Guid.Empty)
        {
            throw new ArgumentException("ConversationId cannot be empty.", nameof(conversationId));
        }

        if (string.IsNullOrWhiteSpace(content))
        {
            throw new ArgumentException("Content cannot be empty.", nameof(content));
        }

        Id = id;
        ConversationId = conversationId;
        Role = role;
        Content = content;
        CreatedAt = createdAt;
    }
}
